### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by gradyrobbins** [nss-day-cohort-29/nutshell-sunset-chaserz#9]
Entity relationship diagram.

**Comment by zwcrawford** [comment]
![image](https://user-images.githubusercontent.com/1837102/50909968-7e179980-13f2-11e9-809d-845d4d215ade.png)

**Comment by zwcrawford** [comment]
![image](https://user-images.githubusercontent.com/1837102/50914858-25013300-13fd-11e9-8778-9871b59726bf.png)

**Comment by zwcrawford** [comment]
![image](https://user-images.githubusercontent.com/1837102/50915979-8d511400-13ff-11e9-9b7b-8d54a5d3eec6.png)

**Comment by zwcrawford** [comment]
![image](https://user-images.githubusercontent.com/1837102/50917082-529cab00-1402-11e9-921f-9703a5fd5d7e.png)

**Comment by zwcrawford** [comment]
![image](https://user-images.githubusercontent.com/1837102/50925243-5d156f80-1417-11e9-93af-c48d954eb4c5.png)

**Comment by zwcrawford** [comment]
^^^ Approved by Emily!
